A/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('ticket/', include('ticket.urls', namespace='ticket')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('register/', views.RegisterView.as_view(), name='register'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('logout/', views.LogoutView.as_view(), name='logout'),
    path('admin-dashboard/', views.AdminView.as_view(), name='admin'),

]

ticket/urls.py
from django.urls import path

from . import views

app_name = 'ticket'
urlpatterns = [

    path('detail/<ticket_id>/', views.TicketDetailView.as_view(), name='ticket-detail'),
    path('create/', views.TicketCreateView.as_view(), name='ticket-create'),
    path('close/<ticket_id>/', views.TicketCloseView.as_view(), name='ticket-close'),
    path('open/<ticket_id>/', views.TicketOpenView.as_view(), name='ticket-open'),
    path('lists-open/', views.TicketOpenListView.as_view(), name='ticket-open-lists'),
    path('in-porgress-list/', views.TicketInProgressListView.as_view(), name='ticket-in-progress-lists'),
    path('close-list/', views.TicketCloseListView.as_view(), name='ticket-close-lists'),

]

templates/include/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}" >
            {{ message }}
        </div>
    {% endfor %}

{% endif %}

templates/include/navbar.html
<!-- Navbar -->
<nav class="navbar navbar-expand-lg">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home:home' %}">SystemTicketing</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'home:home' %}">Home</a>
                </li>
                {% if request.user.is_authenticated %}

                    {% if not request.user.is_staff  %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:profile' request.user.username %}">Profile</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'ticket:ticket-create' %}">Create Ticket</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'home:admin' %}">Admin Dashboard</a>
                        </li>
                    {% endif %}

                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:login' %}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home:register' %}">Register</a>
                    </li>
                {% endif %}


            </ul>
        </div>
    </div>
</nav>